"""OpenRouter multi-key rotation helpers for OpenManus / local CLIs."""

from __future__ import annotations

import itertools
import os
import threading
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Optional


DEFAULT_OPENROUTER_BASE = 'https://openrouter.ai/api/v1'


@dataclass
class OpenRouterConfig:
    api_keys: List[str]
    model: str = 'openrouter/auto'
    base_url: str = DEFAULT_OPENROUTER_BASE

    @property
    def key_count(self) -> int:
        return len(self.api_keys)


class KeyRotator:
    """Round-robin OpenRouter API key pool (thread-safe)."""

    def __init__(self, keys: Iterable[str]):
        cleaned = [k.strip() for k in keys if k and k.strip()]
        if not cleaned:
            raise ValueError(
                'No OpenRouter API keys found. Set OPENROUTER_API_KEYS '
                '(comma-separated) or provide a keys file.'
            )
        self._keys = cleaned
        self._cycle = itertools.cycle(range(len(cleaned)))
        self._lock = threading.Lock()

    @property
    def count(self) -> int:
        return len(self._keys)

    def next_key(self) -> str:
        with self._lock:
            return self._keys[next(self._cycle)]

    def as_list(self) -> List[str]:
        return list(self._keys)


def load_keys_from_env() -> List[str]:
    """
    Load keys from environment.

    Supported:
      OPENROUTER_API_KEYS=key1,key2,key3
      OPENROUTER_API_KEY=single_key
      OPENROUTER_API_KEY_1 ... OPENROUTER_API_KEY_12
    """
    keys: List[str] = []

    multi = os.getenv('OPENROUTER_API_KEYS', '').strip()
    if multi:
        keys.extend(part.strip() for part in multi.split(',') if part.strip())

    single = os.getenv('OPENROUTER_API_KEY', '').strip()
    if single and single not in keys:
        keys.append(single)

    for index in range(1, 33):
        value = os.getenv(f'OPENROUTER_API_KEY_{index}', '').strip()
        if value and value not in keys:
            keys.append(value)

    return keys


def load_keys_from_file(path: str | Path) -> List[str]:
    """Load one key per line from a local file (ignores blanks and # comments)."""
    file_path = Path(path).expanduser()
    if not file_path.exists():
        raise FileNotFoundError(f'Keys file not found: {file_path}')

    keys: List[str] = []
    for line in file_path.read_text(encoding='utf-8').splitlines():
        text = line.strip()
        if not text or text.startswith('#'):
            continue
        # Allow KEY=value lines
        if '=' in text and not text.startswith('sk-'):
            _, _, maybe = text.partition('=')
            text = maybe.strip().strip('"').strip("'")
        if text:
            keys.append(text)
    return keys


def resolve_keys(keys_file: Optional[str] = None, extra_keys: Optional[Iterable[str]] = None) -> List[str]:
    keys = load_keys_from_env()
    if keys_file:
        keys.extend(load_keys_from_file(keys_file))
    if extra_keys:
        keys.extend(k.strip() for k in extra_keys if k and k.strip())

    # Dedupe while preserving order
    seen = set()
    unique: List[str] = []
    for key in keys:
        if key not in seen:
            seen.add(key)
            unique.append(key)
    return unique


def build_openmanus_llm_config(
    *,
    model: str,
    api_key: str,
    base_url: str = DEFAULT_OPENROUTER_BASE,
) -> str:
    """Return a TOML snippet for OpenManus config.toml [llm] section."""
    return (
        '[llm]\n'
        f'model = "{model}"\n'
        f'base_url = "{base_url}"\n'
        f'api_key = "{api_key}"\n'
        'max_tokens = 8192\n'
        'temperature = 0.0\n'
    )


def write_openmanus_config(
    output_path: str | Path,
    *,
    model: str,
    api_key: str,
    base_url: str = DEFAULT_OPENROUTER_BASE,
) -> Path:
    path = Path(output_path).expanduser()
    path.parent.mkdir(parents=True, exist_ok=True)
    content = (
        '# Generated by openmanus_openrouter CLI — do not commit real keys\n'
        + build_openmanus_llm_config(model=model, api_key=api_key, base_url=base_url)
    )
    path.write_text(content, encoding='utf-8')
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass
    return path
